name: Build Linux Flatpak

on:
  push:
    branches: [main]
    paths:
      - "linux/**"
      - ".github/workflows/linux.yml"
      - "Makefile"
  pull_request:
    branches: [main]
    paths:
      - "linux/**"
      - ".github/workflows/linux.yml"
      - "Makefile"
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run ColorModel Unit Tests
        run: |
          make test-linux

  flatpak:
    name: Build Flatpak Bundle (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            os: ubuntu-latest
          - arch: aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    needs: test
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Flatpak Bundle
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ContrastChecker-${{ matrix.arch }}.flatpak
          manifest-path: linux/io.github.svinkle.ContrastChecker.yml
          run-tests: false
          arch: ${{ matrix.arch }}

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ContrastChecker-Linux-${{ matrix.arch }}-Flatpak
          path: ContrastChecker-${{ matrix.arch }}.flatpak
